"""Clean initial migration

Revision ID: 30d60ab0be65
Revises: 61f9cc84c56a
Create Date: 2025-05-08 10:17:32.486650

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '30d60ab0be65'
down_revision = '61f9cc84c56a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory_reservations')
    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.drop_column('expires_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))

    op.create_table('inventory_reservations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cart_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('variant_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'EXPIRED', 'COMPLETED', 'CANCELLED', name='reservationstatus'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], name='inventory_reservations_cart_id_fkey'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='inventory_reservations_product_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='inventory_reservations_user_id_fkey'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], name='inventory_reservations_variant_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='inventory_reservations_pkey')
    )
    # ### end Alembic commands ###
