"""Clean initial migration

Revision ID: 61f9cc84c56a
Revises: b1f902c5bf6a
Create Date: 2025-05-05 01:13:36.946492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61f9cc84c56a'
down_revision = 'b1f902c5bf6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.drop_column('expires_at')

    # ### end Alembic commands ###
