"""Rename metadata to transaction_metadata in PaymentTransaction

Revision ID: 72cacde70d21
Revises: 8fd4a40725f3
Create Date: 2025-05-31 08:17:13.515975

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '72cacde70d21'
down_revision = '8fd4a40725f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('tags',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('tags',
               existing_type=sa.Text(),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               existing_nullable=True)

    # ### end Alembic commands ###
