"""Rename metadata to transaction_metadata in PaymentTransaction

Revision ID: 8fd4a40725f3
Revises: 
Create Date: 2025-05-26 18:28:22.380272

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8fd4a40725f3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mpesa_transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_mpesa_transactions_account_reference')
        batch_op.drop_index('ix_mpesa_transactions_checkout_request_id')
        batch_op.drop_index('ix_mpesa_transactions_merchant_request_id')
        batch_op.drop_index('ix_mpesa_transactions_mpesa_receipt_number')
        batch_op.drop_index('ix_mpesa_transactions_transaction_id')

    op.drop_table('mpesa_transactions')
    with op.batch_alter_table('payment_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('currency', sa.String(length=3), nullable=True))
        batch_op.add_column(sa.Column('provider', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('provider_transaction_id', sa.String(length=100), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('transaction_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.create_foreign_key(None, 'orders', ['order_id'], ['id'])

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.ARRAY(sa.String()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('tags')

    with op.batch_alter_table('payment_transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('transaction_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('provider_transaction_id')
        batch_op.drop_column('provider')
        batch_op.drop_column('currency')
        batch_op.drop_column('order_id')

    op.create_table('mpesa_transactions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('transaction_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('checkout_request_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('merchant_request_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('mpesa_receipt_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('account_reference', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('transaction_desc', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('result_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('result_desc', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('request_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('response_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('processed_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('transaction_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='mpesa_transactions_pkey')
    )
    with op.batch_alter_table('mpesa_transactions', schema=None) as batch_op:
        batch_op.create_index('ix_mpesa_transactions_transaction_id', ['transaction_id'], unique=False)
        batch_op.create_index('ix_mpesa_transactions_mpesa_receipt_number', ['mpesa_receipt_number'], unique=False)
        batch_op.create_index('ix_mpesa_transactions_merchant_request_id', ['merchant_request_id'], unique=False)
        batch_op.create_index('ix_mpesa_transactions_checkout_request_id', ['checkout_request_id'], unique=False)
        batch_op.create_index('ix_mpesa_transactions_account_reference', ['account_reference'], unique=False)

    # ### end Alembic commands ###
