"""Clean initial migration

Revision ID: b1f902c5bf6a
Revises: f6af85d035d5
Create Date: 2025-05-03 13:52:02.760589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1f902c5bf6a'
down_revision = 'f6af85d035d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reorder_level', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_inventory_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_variant_id'), ['variant_id'], unique=False)
        batch_op.create_unique_constraint('uix_inventory_product_variant', ['product_id', 'variant_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_constraint('uix_inventory_product_variant', type_='unique')
        batch_op.drop_index(batch_op.f('ix_inventory_variant_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_product_id'))
        batch_op.drop_column('created_at')
        batch_op.drop_column('status')
        batch_op.drop_column('reorder_level')

    # ### end Alembic commands ###
