"""Initial migration

Revision ID: d57f4599b6e8
Revises: 
Create Date: 2025-05-01 14:43:24.328680

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd57f4599b6e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.drop_column('shipping_cost')
        batch_op.drop_column('item_count')
        batch_op.drop_column('is_taxable')
        batch_op.drop_column('guest_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('reset_token')
        batch_op.drop_column('reset_token_expires')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token_expires', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('reset_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guest_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_taxable', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('item_count', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('shipping_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
