"""Recreating lost migrations

Revision ID: ffad036f21f5
Revises: 
Create Date: 2025-03-21 08:55:43.519949

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ffad036f21f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('specifications')
        batch_op.drop_column('colors')
        batch_op.drop_column('sizes')
        batch_op.drop_column('rating')
        batch_op.drop_column('reviews_count')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reviews_count', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('sizes', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('colors', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('specifications', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
